config/routes.rb
ExerciseApp::Application.routes.draw do
	resources :users
	
	resources :sessions, only: [:new, :create, :destroy]
	
	match '/signup', to: 'users#new'
	match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
	get   '/login', :to => 'sessions#new', :as => :login
	match '/auth/:provider/callback', :to => 'sessions#create'
	match '/auth/failure', :to => 'sessions#failure'
	resources :categories do
		collection do
			get :picture
		end
		member do
      get :likepage
    end
	end
	match '/search' => 'categories#search'
	
	resources :glossaries do
		member do
			get :expand
			get :collapse
		end
	end
	
	resources :optional_accessories do
		member do
			get :expand
			get :collapse
		end
	end
 	
 	resources :general_tips do
		member do
			get :expand
			get :collapse
		end
	end
 	
	resources :exercises do
		member do
			get :expand
			get :collapse
      get :likepage
		end
		collection do
			get :data
			get :media_display
		end
	end

	resources :videos do
		member do
			get :display
		end
	end
	
	resources :exercise_pictures  do
		member do
			get :display
		end
	end
	
	resources :workouts do
		member do
      get :likepage
    end
	end
	match '/signup',  to: 'users#new'
  match '/home', to: 'pages#home'
	root to: 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name
	has_many :category_exercises, :foreign_key => "category_id",
                                   			 :class_name => "ExerciseCategory",
                                   			 :dependent => :destroy
  has_many :exercises, :through => :category_exercises
  
 	has_many :category_pictures, :foreign_key => "category_id",
                           		 :dependent => :destroy
  def included_exercise?(exercise)
    category_exercises.find_by_exercise_id(exercise)
  end

  def include_exercise!(exercise)
    category_exercises.create!(:exercise_id => exercise.id)
  end
  
  def include_exercise_id!(exercise_id)
    category_exercises.create!(:exercise_id => exercise_id)
  end
  
	def exclude_exercise!(exercise)
    category_exercises.find_by_exercise_id(exercise).destroy
  end
  
  def width
  	(category_pictures.count-1)*200
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  	@title = "All Exercises | Rubberbanditz Exercise Library"
		respond_to do |format|
			format.html
			format.js
		end
  end
  
  def likepage
		@category = Category.find(params[:id])
		render :action => 'likepage', :layout => false
  end
	
	
  def show
  	@category = Category.find(params[:id])
		@exercises = @category.exercises
		@name = @category.name
		@title = @name + " | Rubberbanditz Exercise Library"
		@showDesc = true
		respond_to do |format|
			format.html
			format.js
		end
  end
  
  def edit
  	@category = Category.find(params[:id])
  	@title = "Edit Category"
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      flash[:success] = "Profile updated."
    	redirect_to categories_path
    else
      @title = "Edit Category"
      render 'edit'
    end
  end

	def destroy
		Category.find(params[:id]).destroy
    flash[:success] = "Category destroyed."
    redirect_to categories_path
  end
  
  def new
  	@category = Category.new
  	@title = "New Category"
  end
  
  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to categories_path
    else
      @title = "Sign up"
      render 'new'
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), :remote => true, :id => category.name %><br/>

app/views/categories/_loaded_content.html.erb
<div class="sidebar">
	<h1> CATEGORY </h1>
	<h2 class="sbbutton" id="All">All</h2>
		<%= render Category.all %>
	<h1> WORKOUT </h1>
		<%= render Workout.all %>
	<h1> EXTRA INFORMATION </h1>
	<h2 class="sbbutton" id="Glossary">Glossary</h2>
	<h2 class="sbbutton" id="Accessory">Accessory Descriptions</h2>
	<h2 class="sbbutton" id="GT">General Tips</h2>
</div>
<div class="descbar">
</div>
<div class="exercises">
	<table class="exercises">
		<%= render Exercise.all %>
	</table>
</div>
<script>
	$("h2#All").click(function () {
		$("table.exercises").html("<%= escape_javascript(render(Exercise.all)) %>");
		$("div.sidebar h2").removeClass("highlight");
		$(this).addClass("highlight");
	}); 
	$("h2#Glossary").click(function () {
		$("table.exercises").html("<%= escape_javascript(render(Glossary.all)) %>");
		$("div.sidebar h2").removeClass("highlight");
		$(this).addClass("highlight");
	}); 
	$("h2#Accessory").click(function () {
		$("table.exercises").html("<%= escape_javascript(render(OptionalAccessory.all)) %>");
		$("div.sidebar h2").removeClass("highlight");
		$("h2#Accessory").addClass("highlight");
	}); 
	$("h2#GT").click(function () {
		$("table.exercises").html("<%= escape_javascript(render(GeneralTip.all)) %>");
		$("div.sidebar h2").removeClass("highlight");
		$(this).addClass("highlight");
	}); 
	$("input.search_bar").click(function () {
		$(this).css("color","#000");
		$(this).css("font-style","normal");
	}); 
	$(function() {
		$("h2#<%= @sel %>").click();
		if ("<%= @clickex %>" == "true") {
			$("td.<%= @id %>").click();
			document.getElementById("<%= @id %>").scrollIntoView();
		}
	}); 
</script>

app/views/categories/_search_result.html.erb
<% if object.class.name == "Exercise" %>
	<%= link_to object.name, exercise_path(object) %>
	<p> <%= object.description %> </p>
<% end %>

app/views/categories/_title.html.erb
<% if category.category_pictures.count > 0 %>
	<div class="catimage">
		<table class="img">
			<tr>
				<% category.category_pictures.each do |cp| %>
					<td><%= image_tag cp.get_site %>	</td>
				<% end %>
			</tr>
		</table>
	</div>
	<div class="im back">
		<div class="text">&lt</div>
	</div>
	<div class="im forward">
		<div class="text">&gt</div>
	</div>
<% end %>
<div class="dright">
	<h1><%= category.name.upcase %></h1>
	<%= category.sci_name %><br />
	<%= category.description %><br />
	<div class="fb-like" data-href="<%= likepage_category_path(category) %>" data-send="true" data-width="450" data-show-faces="true"></div>
</div>
<script>
function changeColors() {
  if ($("div.catimage").scrollLeft() == 0) {
		$("div.back").css("color","#ccc");
		$("div.back").css("background","none");
		$("div.back").css("cursor","default");
	} else {
		$("div.back").css("color","#000");
	}
	if ($("div.catimage").scrollLeft() >= parseInt("<%= category.width %>")) {
		$("div.forward").css("color","#ccc");
		$("div.forward").css("background","none");
		$("div.forward").css("cursor","default");
	} else {
		$("div.forward").css("color","#000");
	}
};
$("div.back").click(function () {
		$("div.catimage").scrollLeft($("div.catimage").scrollLeft()-200);
		changeColors()
}); 
$("div.forward").click(function () {
	$("div.catimage").scrollLeft($("div.catimage").scrollLeft()+200);
	changeColors()
}); 
$("div.back").hover(
  function () {
    if ($("div.catimage").scrollLeft() == 0) {
			$("div.back").css("background","none");
			$("div.back").css("cursor","default");
			$("div.back").css("opacity","1.0");
		} else {
			$("div.back").css("background","#666");
			$("div.back").css("cursor","pointer");
			$("div.back").css("opacity","0.4");
		}
  }, 
  function () {
			$("div.back").css("background","none");
			$("div.back").css("cursor","default");
			$("div.back").css("opacity","1.0");
  }
);
$("div.forward").hover(
  function () {
    if ($("div.catimage").scrollLeft() >= parseInt("<%= category.width %>")) {
			$("div.forward").css("background","none");
			$("div.forward").css("cursor","default");
			$("div.forward").css("opacity","1.0");
		} else {
			$("div.forward").css("background","#666");
			$("div.forward").css("cursor","pointer");
			$("div.forward").css("opacity","0.4");
		}
  }, 
  function () {
    	$("div.forward").css("background","none");
			$("div.forward").css("cursor","default");
			$("div.forward").css("opacity","1.0");
  }
);
changeColors()
if (parseInt("<%= category.category_pictures.count %>") > 0) {
	$("div.dright").css("left","210px");
}
$('div.fb-like').attr('data-width',$('.dright').width()-15)
</script>

app/views/categories/display.js.erb
$("div.sidebar a").removeClass("highlight");
$("a#<%= @name %>").addClass("highlight");
if ("<%= @showDesc %>" === "true") {
	$("div.descbar").show();
	$("div.exercises").css("top","150px");
	$("div.descbar").html("<%= escape_javascript(render('categories/title', :category => @category)) %>");
} else {
	$("div.descbar").hide();
	$("div.exercises").css("top","0px");
	$("div.descbar").html("");
}
$("table.exercises").html("<%= escape_javascript(render(@exercises)) %>");

app/views/categories/displayall.js.erb
$("div.sidebar h2").removeClass("highlight");
$("h2#<%= @name %>").addClass("highlight");
$("div.descbar").hide();
$("div.exercises").css("top","0px");
$("table.exercises").html("<%= escape_javascript(render(Exercises.all)) %>");

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_for(@category) do |f| %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="actions">
	<%= f.submit "Save" %>
</div>
<% end %>

app/views/categories/index.html.erb
<div class="descbar" style="display:none">
</div>
<div class="exercises" style="top:0px">
	<table class="exercises"><%= render Exercise.all %>
	<tr>
		<td>
		<% if signed_in? %>
			<%= link_to "New Exercise", new_exercise_path %>
		<% end %>
		</td>
	</tr></table>
</div>

app/views/categories/index.js.erb
$("div.sidebar a").removeClass("highlight");
$("a#All").addClass("highlight");
$("div.descbar").hide();
$("div.results").hide();
$("div.exercises").css("top","0px");
$("div.descbar").html("");
$("table.exercises").html("<%= escape_javascript(render(Exercise.all)) %>");
document.title = "<%= @title %>"
window.history.replaceState("","","<%= root_path %>");

app/views/categories/likepage.html.erb
<!DOCTYPE html>
<html xmlns:og="http://ogp.me/ns#">
  <head>
    <title><%= @category.name %></title>
		<meta property="fb:app_id" content="299584876770579"/>
		<meta property="fb:admins" content="JasonMcMains"/ > 
		<meta property="og:title" content="<%= @category.name %>"/>
		<meta property="og:type" content="website"/>
		<meta property="og:site_name" content="Rubberbanditz Exercise App"/ >
		<meta property="og:url" content="<%= likepage_category_path(@category) %>"/>
		<meta property="og:image" content="<%= @category.category_pictures.first.get_site %>" />
		<meta property="og:description" content="This is one of Rubberbanditz great workouts!"/>
  </head>
  <body>
<script>
  window.location = "<%= category_path(@category) %>";
</script>

  </body>
</html>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_for(@category) do |f| %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="actions">
	<%= f.submit "Save" %>
</div>
<% end %>

app/views/categories/search.html.erb
<div class="descbar" style="display:none">
</div>
<div class="exercises" style="top:0px">
	<table class="exercises"></table>
	<div class="results">
	<ul>
		<%= pluralize @results["matches"], "match" %><br />
		<% @results["results"].each do |r| %>
		<li>
			<% if r["__type"] == "Exercise" %>
				<%= link_to r["name"], exercise_path(r["__id"]) %> <br/>
			<% elsif r["__type"] == "GeneralTip" %>
				<%= link_to r["name"], general_tip_path(r["__id"]) %> <br/>
			<% elsif r["__type"] == "Glossary" %>
				<%= link_to r["term"], glossary_path(r["__id"]) %><br/>
			<% elsif r["__type"] == "OptionalAccessory" %>
				<%= link_to r["name"], optional_accessory_path(r["__id"]) %> <br/>
			<% end %>
				<p><%= raw r["snippet___any"] %></p></li>
		<% end %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="descbar">
	<%= render('categories/title', :category => @category) %>
</div>
<div class="exercises" style="top:150px">
	<table class="exercises"><%= render @category.exercises %></table>
</div>
		<div class="results">
		</div>
<script>
$("div.sidebar a").removeClass("highlight");
$("a#<%= @category.name %>").addClass("highlight");
window.location("<%= category_path(@category) %>");
</script>

app/views/categories/show.js.erb
$("div.sidebar a").removeClass("highlight");
$("a#<%= @name %>").addClass("highlight");
$("div.descbar").show();
$("div.exercises").css("top","150px");
$("div.descbar").html("<%= escape_javascript(render('categories/title', :category => @category)) %>");
$("table.exercises").html("<%= escape_javascript(render(@category.exercises)) %>");
window.history.replaceState("","","<%= category_path(@category) %>");
document.title = "<%= @title %>"
$("div.results").hide();
FB.XFBML.parse($(".dright")[0]);